"use client"

import {
  AppointmentFormSchema,
  AppointmentFormTemplate,
  createAppointmentModel,
} from "@/models/AppointmentModel"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import ApplicationForm from "@/components/ApplicationForm/ApplicationForm"
import { ApplicationFormProvider } from "@/components/ApplicationForm/ApplicationFormContext"

export default function AppointmentPage() {
  return (
    <main className="mx-auto mt-3">
      <div className="mb-8 flex flex-col items-center justify-center text-center">
        <h1 className=" text-4xl font-bold">Appointment Applications</h1>
        <p className=" text-gray-600">
          Apply for your Appointment online.
          <br />
          Fill out the form below to start your application.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-8 ">
        <Card className="h-fit w-full ">
          <CardHeader>
            <CardTitle>Application Information</CardTitle>
          </CardHeader>

          {/* Form is being generated by the ApplicationForm comp through the Template, and the form validation, submission & logic is being handled by the ApplicationFormContext */}
          <CardContent className="">
            <ApplicationFormProvider
              table_name="scheduled_appointments"
              createApplicationModel={createAppointmentModel}
              modelFormSchema={AppointmentFormSchema}
            >
              <ApplicationForm template={AppointmentFormTemplate} />
            </ApplicationFormProvider>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
